# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialog_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 230)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 20, 54, 21))
        self.label.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
"text-decoration: underline;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(41, 59, 284, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 102, 85, 17))
        self.label_3.setStyleSheet("font: 9pt \"Baskerville Old Face\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 125, 54, 17))
        self.label_4.setStyleSheet("font: 9pt \"Baskerville Old Face\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 148, 49, 17))
        self.label_5.setStyleSheet("font: 9pt \"Baskerville Old Face\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(39, 190, 281, 16))
        self.label_6.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "About !"))
        self.label_2.setText(_translate("Dialog", "This software was built as a demo project using :"))
        self.label_3.setText(_translate("Dialog", "+ Qt Designer"))
        self.label_4.setText(_translate("Dialog", "+ Python"))
        self.label_5.setText(_translate("Dialog", "+ PyQt5"))
        self.label_6.setText(_translate("Dialog", "https://github.com/oron-sinaa/"))
