# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUWSGBW.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import toolbar_resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(960, 540)
        self.action_New = QAction(MainWindow)
        self.action_New.setObjectName(u"action_New")
        icon = QIcon()
        icon.addFile(u":/tooldbar_images/new_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_New.setIcon(icon)
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        icon1 = QIcon()
        icon1.addFile(u":/tooldbar_images/open_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/tooldbar_images/open_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.action_Open.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/tooldbar_images/save_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/tooldbar_images/save_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionSave.setIcon(icon2)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon3 = QIcon()
        icon3.addFile(u":/tooldbar_images/zcut.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionCut.setIcon(icon3)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon4 = QIcon()
        icon4.addFile(u":/tooldbar_images/copy_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon4.addFile(u":/tooldbar_images/copy_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionCopy.setIcon(icon4)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon5 = QIcon()
        icon5.addFile(u":/tooldbar_images/paste_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon5.addFile(u":/tooldbar_images/paste_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionPaste.setIcon(icon5)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon6 = QIcon()
        icon6.addFile(u":/tooldbar_images/undo_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon6.addFile(u":/tooldbar_images/undo_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionUndo.setIcon(icon6)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon7 = QIcon()
        icon7.addFile(u":/tooldbar_images/redo_light.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon7.addFile(u":/tooldbar_images/redo_dark.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionRedo.setIcon(icon7)
        self.actionDark_Light = QAction(MainWindow)
        self.actionDark_Light.setObjectName(u"actionDark_Light")
        self.actionDark_Light.setCheckable(True)
        icon8 = QIcon()
        icon8.addFile(u":/tooldbar_images/mode_light.png", QSize(), QIcon.Normal, QIcon.Off)
        icon8.addFile(u":/tooldbar_images/mode_dark.png", QSize(), QIcon.Normal, QIcon.On)
        self.actionDark_Light.setIcon(icon8)
        font = QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.actionDark_Light.setFont(font)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave_2 = QAction(MainWindow)
        self.actionSave_2.setObjectName(u"actionSave_2")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionCut_2 = QAction(MainWindow)
        self.actionCut_2.setObjectName(u"actionCut_2")
        self.actionCopy_2 = QAction(MainWindow)
        self.actionCopy_2.setObjectName(u"actionCopy_2")
        self.actionPaste_2 = QAction(MainWindow)
        self.actionPaste_2.setObjectName(u"actionPaste_2")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionFind = QAction(MainWindow)
        self.actionFind.setObjectName(u"actionFind")
        self.actionColored_text = QAction(MainWindow)
        self.actionColored_text.setObjectName(u"actionColored_text")
        self.actionAbout_2 = QAction(MainWindow)
        self.actionAbout_2.setObjectName(u"actionAbout_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")

        self.verticalLayout.addWidget(self.textEdit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 960, 26))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menuF_ormat = QMenu(self.menubar)
        self.menuF_ormat.setObjectName(u"menuF_ormat")
        self.menu_About = QMenu(self.menubar)
        self.menu_About.setObjectName(u"menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menuF_ormat.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave_2)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Edit.addAction(self.actionCut_2)
        self.menu_Edit.addAction(self.actionCopy_2)
        self.menu_Edit.addAction(self.actionPaste_2)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionDelete)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionFind)
        self.menuF_ormat.addAction(self.actionColored_text)
        self.menu_About.addAction(self.actionAbout_2)
        self.toolBar.addAction(self.action_New)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDark_Light)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_New.setText(QCoreApplication.translate("MainWindow", u"New...", None))
        self.action_New.setIconText(QCoreApplication.translate("MainWindow", u"New...", None))
#if QT_CONFIG(tooltip)
        self.action_New.setToolTip(QCoreApplication.translate("MainWindow", u"Create a new file", None))
#endif // QT_CONFIG(tooltip)
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.action_Open.setIconText(QCoreApplication.translate("MainWindow", u"Open...", None))
#if QT_CONFIG(tooltip)
        self.action_Open.setToolTip(QCoreApplication.translate("MainWindow", u"Open an existing file", None))
#endif // QT_CONFIG(tooltip)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save...", None))
        self.actionSave.setIconText(QCoreApplication.translate("MainWindow", u"Save...", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save the file on local disk", None))
#endif // QT_CONFIG(tooltip)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut...", None))
#if QT_CONFIG(tooltip)
        self.actionCut.setToolTip(QCoreApplication.translate("MainWindow", u"Cut the selected text", None))
#endif // QT_CONFIG(tooltip)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy...", None))
#if QT_CONFIG(tooltip)
        self.actionCopy.setToolTip(QCoreApplication.translate("MainWindow", u"Copy the selected text", None))
#endif // QT_CONFIG(tooltip)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste...", None))
#if QT_CONFIG(tooltip)
        self.actionPaste.setToolTip(QCoreApplication.translate("MainWindow", u"Paste text on the clipboard", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo...", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo previous action", None))
#endif // QT_CONFIG(tooltip)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo...", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"Redo the last undone action", None))
#endif // QT_CONFIG(tooltip)
        self.actionDark_Light.setText(QCoreApplication.translate("MainWindow", u"Dark Mode...", None))
        self.actionDark_Light.setIconText(QCoreApplication.translate("MainWindow", u"Dark/Light...", None))
#if QT_CONFIG(tooltip)
        self.actionDark_Light.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle between dark and light themes", None))
#endif // QT_CONFIG(tooltip)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.actionSave_2.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionCut_2.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionCopy_2.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste_2.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.actionFind.setText(QCoreApplication.translate("MainWindow", u"Find", None))
        self.actionColored_text.setText(QCoreApplication.translate("MainWindow", u"Colored text", None))
        self.actionAbout_2.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuF_ormat.setTitle(QCoreApplication.translate("MainWindow", u"F&ormat", None))
        self.menu_About.setTitle(QCoreApplication.translate("MainWindow", u"&Info", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

